


dw_tempo_rib_preto:
  target: dw
  outputs:
    stg:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server'
      server: 172.40.0.21
      port: 1433
      database: STG_DW_TEMPO     # origem
      schema: dbo
      user: sa
      password: YourStrongP@ssw0rd!
      encrypt: true
      trust_cert: true

    dw:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server'
      server: 172.40.0.21
      port: 1433
      database: DW_TEMPO         # destino
      schema: dbo
      user: sa
      password: YourStrongP@ssw0rd!
      encrypt: true
      trust_cert: true
