DROP TABLE IF EXISTS FT_CLIMA;
DROP TABLE IF EXISTS DIM_CALENDARIO;
DROP TABLE IF EXISTS DIM_CIDADE;

CREATE TABLE DIM_CIDADE (
    ID_CIDADE INT NOT NULL PRIMARY KEY,
    NOME_CIDADE NVARCHAR(255)
);


CREATE TABLE DIM_CALENDARIO (
    DATA_CALENDARIO DATE NOT NULL,
    HORA TIME NOT NULL,
    ANO INT,
    MES INT,
    DIA INT,
    TRIMESTRE INT,
    SEMANA_DO_ANO INT,
    DIA_DA_SEMANA INT,
    NOME_MES VARCHAR(20),
    NOME_DIA_SEMANA VARCHAR(20),
    ANO_MES VARCHAR(7),
    TURNO VARCHAR(20),
    PRIMARY KEY (DATA_CALENDARIO, HORA)
);


CREATE TABLE FT_CLIMA (
    ID_CIDADE INT NOT NULL,
    DATA_CONSULTA DATE NOT NULL,
    HORA_CONSULTA TIME NOT NULL,
    TEMPERATURA DECIMAL(5,2),
    PRESSAO DECIMAL(7,2),
    UMIDADE SMALLINT,
    VELOCIDADE_VENTO DECIMAL(5,2),
    ANGULO_VENTO DECIMAL(5,2),
    NOME_CIDADE NVARCHAR(255),

  

    CONSTRAINT FK_FT_CLIMA_CIDADE FOREIGN KEY (ID_CIDADE)
        REFERENCES DIM_CIDADE(ID_CIDADE),

    CONSTRAINT FK_FT_CLIMA_CALENDARIO FOREIGN KEY (DATA_CONSULTA, HORA_CONSULTA)
        REFERENCES DIM_CALENDARIO(DATA_CALENDARIO, HORA)
);



SELECT *
FROM DIM_CALENDARIO;

SELECT *
FROM FT_CLIMA;


