CREATE TABLE dbo.LogOperacoesBanco (
    IdLog INT IDENTITY(1,1) PRIMARY KEY,

    Consulta NVARCHAR(MAX)  NULL,
    Nome VARCHAR(200),
    NomeArquivo VARCHAR(200),
    Funcao VARCHAR(200),
    NumeroLinha SMALLINT,
    url NVARCHAR(MAX) NULL,
    Codigo INT NULL,
    JsonRetorno NVARCHAR(MAX) NULL,
    Mensagem VARCHAR(100),
    NIVEL_LOG NVARCHAR(20) NULL,
    DataInsercao DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT CHK_NIVEL_LOG CHECK (NIVEL_LOG IN ('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL')),
);

SELECT *
FROm LogOperacoesBanco;

TRUNCATE TABLE LogOperacoesBanco;

DROP TABLE LogOperacoesBanco;

SELECT TABLE_SCHEMA, TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'LogOperacoesBanco';