CREATE TABLE STG_DADOS_TEMPO (
    ID_CIDADE INT,
    NOME VARCHAR(60),
    TEMPERATURA DECIMAL(5, 2),   -- ex: permite valores até 999.99
    PRESSAO DECIMAL(7, 2),       -- ex: permite valores até 99999.99
    UMIDADE SMALLINT,
    VELOCIDADE_VENTO DECIMAL(5,2),  -- ex: até 999.99
    ANGULO_VENTO DECIMAL(5,2),       -- ex: até 999.99
    DATA_CONSUTA DATETIME
);

select GETDATE()


SELECT * 
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_NAME = 'STG_DADOS_TEMPO';


SELECT *
FROM STG_DADOS_TEMPO;