CREATE TABLE STG_DADOS_TEMPO (
    ID_CIDADE INT,
    NOME VARCHAR(60),
    TEMPERATURA DECIMAL(3, 3),
    PRESSAO DECIMAL(3, 3),
    UMIDADE SMALLINT,
    VELOCIDADE_VENDO DECIMAL(4,3),
    ANGULO_VENTO DECIMAL(4,3)
);

select GETDATE()